---

- hosts: all
  name: 'Converge'
  become: True
  vars:
    __converge_network_devices:
      Debian: 'eth0'
      OpenBSD: 'em0'

  tasks:
    - import_role:
        name: 'ansible-role-network'
      vars:
        network_dns_inet_nameservers:
          - 9.9.9.9

        network_dns_inet6_nameservers:
          - 2606:4700:4700::1111

        network_ethernet_interfaces:
          - device: "{{ __converge_network_devices[ansible_facts['os_family']] }}"
            options:
              mtu: 1492

            inet:
              type: static

              address: 10.0.2.15
              netmask: 255.255.0.0
              broadcast: 10.0.2.255
              gateway: 10.0.2.2

            inet6:
              type: static

              address: fe80::9656:d028:8652:66b6
              prefixlen: 64
