---

- name: 'update device (check file)'
  stat:
    path: "/etc/hostname.{{ item.device }}"
  when: item.state | default('present') == 'present'
  loop: "{{ network_ethernet_interfaces + network_vlan_interfaces }}"
  register: __network_ethernet_update_stat_result

- name: 'update device (backup file)'
  copy:
    src: "/etc/hostname.{{ item.item.device }}"
    dest: "/etc/BKP-hostname.{{ item.item.device }}"
    remote_src: True
    owner: 'root'
    group: 'wheel'
    mode: '0640'
  changed_when: False
  when: >
    item.stat is defined
    and item.stat.exists
  loop: "{{ __network_ethernet_update_stat_result.results }}"

- name: 'update devices (update ethernet config)'
  template:
    src: 'OpenBSD/etc/hostname.if.j2'
    dest: "/etc/hostname.{{ item.device }}"
    owner: 'root'
    group: 'wheel'
    mode: '0640'
  when: item.state | default('present') == 'present'
  loop: "{{ network_ethernet_interfaces }}"
  register: __network_ethernet_update_ethernet_tpl_result
  notify:
    - 'network_reload_listener'
    - 'network_restart_listener'

- name: 'update devices (update vlan config)'
  template:
    src: 'OpenBSD/etc/hostname.vlan.j2'
    dest: "/etc/hostname.{{ item.device }}"
    owner: 'root'
    group: 'wheel'
    mode: '0640'
  when: item.state | default('present') == 'present'
  loop: "{{ network_vlan_interfaces }}"
  register: __network_ethernet_update_vlan_tpl_result
  notify:
    - 'network_reload_listener'
    - 'network_restart_listener'

- name: 'concat results'
  set_fact:
    __network_ethernet_update_tpl_results: "{{ __network_ethernet_update_ethernet_tpl_result.results + __network_ethernet_update_vlan_tpl_result.results }}"

- name: 'update device (ifdown/ifup)'
  shell: |
    mv /etc/hostname.{{ item.device }} /etc/NEW-hostname.{{ item.device }};
    mv /etc/BKP-hostname.{{ item.device }} /etc/hostname.{{ item.device }};
    /sbin/ifconfig {{ item.device }} -alias || true;
    /sbin/ifconfig {{ item.device }} -vnetid || true;
    /sbin/ifconfig {{ item.device }} -inet || true;
    /sbin/ifconfig {{ item.device }} -inet6 || true;
    /sbin/ifconfig {{ item.device }} down || true;
    /usr/bin/pkill -u _dhcp -f "dhclient.*{{ item.device }}" || true;
    mv /etc/NEW-hostname.{{ item.device }} /etc/hostname.{{ item.device }};
    sh /etc/netstart {{ item.device }};
  changed_when: False
  ignore_errors: "{{ item.ignore_errors | default(False) }}"
  async: 30
  poll: 0
  register: __network_ethernet_update_downup_result
  when: >
    item.state | default('present') == 'present'
    and __network_ethernet_update_stat_result.results | json_query("[?stat.exists].item[?device=='" + item.device + "']") | length > 0
    and __network_ethernet_update_tpl_results | json_query("[?changed].item[?device=='" + item.device + "']") | length > 0
  loop: "{{ network_ethernet_interfaces + network_vlan_interfaces }}"

- name: 'update device (ifup)'
  shell: |
    sh /etc/netstart {{ item.device }};
  changed_when: False
  ignore_errors: "{{ item.ignore_errors | default(False) }}"
  when: >
    item.state | default('present') == 'present'
    and __network_ethernet_update_stat_result.results | json_query("[?stat.exists].item[?device=='" + item.device + "']") | length == 0
    and __network_ethernet_update_tpl_results | json_query("[?changed].item[?device=='" + item.device + "']") | length > 0
  loop: "{{ network_ethernet_interfaces + network_vlan_interfaces }}"

- name: 'update device (check status ifdown/ifup)'
  command: 'whoami'
  register: __network_whoami_result
  until: __network_whoami_result.rc == 0
  changed_when: False
  retries: 30
  delay: 1
  when: (network_ethernet_interfaces + network_vlan_interfaces) | length > 0
